<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"
                      Version="18.10.1" />
    <PackageReference Include="MSTest.TestAdapter"
                      Version="4.4.1" />
    <PackageReference Include="MSTest.TestFramework"
                      Version="4.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DotNet2Fox\DotNet2Fox.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="FoxCode\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="..\..\src\FoxCOM\foxcom.exe">
      <Link>foxcom.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>